/**
 * Shell Session Types
 *
 * Types for shell state stored in the chat.state JSON blob.
 * No new database columns are needed — all shell state is persisted
 * within the existing chat state mechanism.
 *
 * @module tools/shell/shell-session.types
 */

/**
 * Shell session state stored in chat.state
 */
export interface ShellSessionState {
  /** Current working directory for shell commands in this chat */
  shellWorkingDirectory?: string;
  /** Map of PIDs to async process records */
  shellAsyncProcesses?: Record<number, AsyncProcessRecord>;
  /** Whether the user has acknowledged the workspace warning for this chat */
  workspaceWarningAcknowledged?: boolean;
}

/**
 * Record of an asynchronous shell process
 */
export interface AsyncProcessRecord {
  /** Process ID */
  pid: number;
  /** The command that was run */
  command: string;
  /** ISO timestamp when the process was started */
  startedAt: string;
  /** Current status of the process */
  status: 'running' | 'complete' | 'timeout' | 'not_found';
  /** Exit code (available when status is 'complete' or 'timeout') */
  exitCode?: number;
  /** Captured stdout (available when status is 'complete' or 'timeout') */
  stdout?: string;
  /** Captured stderr (available when status is 'complete' or 'timeout') */
  stderr?: string;
  /** ISO timestamp when the process completed */
  completedAt?: string;
}

/**
 * Input for shell command execution
 */
export interface ShellCommandRequest {
  /** The command to execute */
  command: string;
  /** Timeout in milliseconds (default: 60000, max: 300000) */
  timeout_ms?: number;
  /** Command arguments/parameters */
  parameters?: string[];
}

/**
 * Result of a synchronous shell command
 */
export interface ShellCommandResult {
  /** Process exit code (0 = success) */
  exit_code: number;
  /** Standard output (truncated to 64KB) */
  stdout: string;
  /** Standard error (truncated to 64KB) */
  stderr: string;
  /** Elapsed time in milliseconds */
  time_elapsed: number;
  /** Any warnings generated by the command checker */
  warnings?: string[];
}

/**
 * Result of an asynchronous shell command
 */
export interface ShellAsyncCommandResult {
  /** Process ID for tracking */
  pid: number;
  /** Current status */
  status: 'running' | 'complete' | 'timeout' | 'not_found';
  /** Stdout (null if still running or not found) */
  stdout: string | null;
  /** Stderr (null if still running or not found) */
  stderr: string | null;
  /** Exit code (available when complete) */
  exit_code?: number;
  /** Elapsed time in milliseconds (available when complete) */
  time_elapsed?: number;
}

/**
 * Context for shell tool execution
 */
export interface ShellToolContext {
  /** User ID */
  userId: string;
  /** Chat ID */
  chatId: string;
  /** Project ID (if chat is in a project) */
  projectId?: string | null;
  /** Character ID (if a character is calling the tool) */
  characterId?: string;
}

/** Default timeout for shell commands (1 minute) */
export const SHELL_TIMEOUT_DEFAULT = 60000;

/** Maximum timeout for shell commands (5 minutes) */
export const SHELL_TIMEOUT_MAX = 300000;

/** Maximum output size in bytes (64KB) */
export const SHELL_MAX_OUTPUT_SIZE = 64 * 1024;
