/**
 * A complete {@link AlmanackReportData} fixture.
 *
 * Every field populated with something distinctive, so the snapshot proves the
 * renderer actually reaches each section rather than quietly dropping one. No
 * clock, no environment: the renderer is pure, and this keeps the snapshot
 * stable across machines.
 *
 * `generatedAt` is rendered through `toLocaleString()`, which is
 * timezone-sensitive — the test pins TZ so the fixture stays portable.
 */

import type { AlmanackReportData } from '@/lib/tools/almanack/types'

export function makeAlmanackFixture(
  overrides: Partial<AlmanackReportData> = {},
): AlmanackReportData {
  return {
    version: '4.9.0',
    nodeEnv: 'test',
    generatedAt: '2026-08-05T12:00:00.000Z',

    runtimeEnvironment: {
      nodeVersion: 'v22.11.0',
      platform: 'darwin',
      arch: 'arm64',
      osType: 'Darwin',
      osRelease: '25.5.0',
      totalMemoryBytes: 68_719_476_736,
      freeMemoryBytes: 8_589_934_592,
      runtimeType: 'node',
      electronShellVersion: null,
      shellCapabilities: ['open-external'],
      uptimeSeconds: 7_265,
      dataDirectory: '/tmp/quilltap-fixture',
      timezone: 'UTC',
    },
    databaseSecurity: {
      passphraseProtected: true,
      databases: [
        { label: 'Main', sizeBytes: 104_857_600, present: true },
        { label: 'LLM Logs', sizeBytes: 52_428_800, present: true },
        { label: 'Mount Index', sizeBytes: 1_073_741_824, present: true },
      ],
      highestAppVersion: '4.9.0',
    },
    backupStatus: [
      {
        label: 'Main',
        count: 3,
        newestDate: '2026-08-04T00:00:00.000Z',
        oldestDate: '2026-08-01T00:00:00.000Z',
        totalSizeBytes: 300_000_000,
      },
      {
        label: 'LLM Logs',
        count: 1,
        newestDate: '2026-08-04T00:00:00.000Z',
        oldestDate: '2026-08-04T00:00:00.000Z',
        totalSizeBytes: 50_000_000,
      },
      { label: 'Mount Index', count: 0, newestDate: null, oldestDate: null, totalSizeBytes: 0 },
    ],
    migrationState: {
      appliedCount: 214,
      lastMigrationId: 'add-llm-logs-profile-columns-v1',
      lastMigrationAt: '2026-08-05T09:00:00.000Z',
      lastMigrationVersion: '4.9.0',
    },

    plugins: {
      enabled: [
        {
          name: 'qtap-plugin-anthropic',
          title: 'Anthropic',
          version: '1.0.45',
          capabilities: ['provider'],
          enabled: true,
          installedFromNpm: false,
        },
      ],
      disabled: [
        {
          name: 'qtap-plugin-mistral',
          title: 'Mistral',
          version: '1.1.0',
          capabilities: ['provider'],
          enabled: false,
          installedFromNpm: true,
        },
      ],
      byCapability: [{ capability: 'provider', count: 2 }],
      npmInstalled: 1,
      bundled: 1,
      pluginConfigRows: 4,
      characterPluginDataRows: 12,
    },
    apiKeyTypes: ['Anthropic API Key'],
    providers: [
      {
        name: 'anthropic',
        displayName: 'Anthropic',
        configured: true,
        capabilities: { chat: true, imageGeneration: false, embeddings: false, webSearch: true },
        requiresApiKey: true,
        requiresBaseUrl: false,
      },
    ],
    modelsByProvider: [{ provider: 'anthropic', models: ['claude-opus-5', 'claude-sonnet-5'] }],
    providerModelCache: [
      {
        provider: 'anthropic',
        total: 12,
        chat: 12,
        image: 0,
        embedding: 0,
        newestUpdatedAt: '2026-08-01T00:00:00.000Z',
      },
    ],
    apiKeyUsage: [
      {
        provider: 'anthropic',
        total: 2,
        active: 1,
        neverUsed: 1,
        lastUsed: '2026-08-04T00:00:00.000Z',
      },
    ],
    cheapLLM: { provider: 'anthropic', model: 'claude-haiku-4-5', profileName: 'Scullery' },
    imagePromptLLM: {},
    embeddingProvider: { provider: 'openai', model: 'text-embedding-3-small', profileName: 'Index' },
    imageProviders: [{ provider: 'openai', displayName: 'OpenAI', models: ['gpt-image-1'] }],
    embeddingProviders: [
      { provider: 'openai', displayName: 'OpenAI', models: ['text-embedding-3-small'] },
    ],
    mcpServers: {
      configured: 2,
      enabled: 1,
      serverNames: ['Household Ledger', 'Weather Glass'],
      autoReconnect: true,
      maxReconnectAttempts: 5,
    },
    themeInfo: {
      activeThemeId: 'madmans-box',
      colorMode: 'dark',
      stats: { total: 6, withDarkMode: 6, withCssOverrides: 4, errors: 0 },
      themes: [
        {
          name: "Madman's Box",
          version: '1.2.0',
          source: 'bundle',
          iconOverrides: 23,
          unknownIconOverrides: 1,
        },
      ],
      themesWithIcons: 1,
      totalIconOverrides: 23,
      totalUnknownIconOverrides: 1,
    },

    databaseStats: {
      characters: 41,
      favoriteCharacters: 7,
      chats: 380,
      memories: 32_104,
      tags: 18,
      projects: 5,
      groups: 3,
      connectionProfiles: {
        total: 9,
        webSearchEnabled: 3,
        toolUseEnabled: 8,
        dangerousCompatible: 2,
      },
      imageProfiles: 3,
      embeddingProfiles: 2,
      promptTemplates: { total: 14, builtIn: 9, custom: 5 },
      roleplayTemplates: { total: 8, builtIn: 6, custom: 2 },
    },
    chatStats: {
      totalEstimatedCostUSD: 12.3456,
      totalPromptTokens: 9_000_000,
      totalCompletionTokens: 1_200_000,
      totalMessages: 24_000,
      agentModeChats: 22,
      dangerousChats: 4,
    },
    chatBreakdown: {
      byType: [
        { chatType: 'salon', count: 340 },
        { chatType: 'autonomous', count: 30 },
        { chatType: 'help', count: 10 },
      ],
      participantHistogram: [
        { participants: 1, chats: 120 },
        { participants: 2, chats: 200 },
        { participants: 5, chats: 60 },
      ],
      pausedChats: 6,
      documentModeChats: 12,
      chatDocumentRows: 41,
      multiDocumentChats: 7,
      chatsWithEquippedOutfit: 88,
      pendingOutfitNotificationChats: 2,
      narrativeTimelineChats: 9,
      chatsWithNonEmptyState: 31,
    },
    autonomousRooms: {
      total: 30,
      byRunState: [
        { runState: 'idle', count: 22 },
        { runState: 'running', count: 5 },
        { runState: 'budgetExhausted', count: 3 },
      ],
      scheduled: 11,
      overdue: 2,
      withTurnBudget: 25,
      withTokenBudget: 30,
      withWallClockBudget: 8,
      withSpendCap: 4,
      destructiveToolsAllowed: 1,
      byVisibility: [
        { visibility: 'owner_only', count: 26 },
        { visibility: 'household', count: 4 },
      ],
    },
    memoryBreakdown: {
      total: 32_104,
      byKind: [
        { kind: 'semantic', count: 28_000 },
        { kind: 'episodic', count: 4_104 },
      ],
      bySource: [
        { source: 'AUTO', count: 31_500 },
        { source: 'MANUAL', count: 604 },
      ],
      byWitnessedContext: [
        { witnessedContext: 'user_present', count: 20_000 },
        { witnessedContext: 'autonomous_room', count: 12_104 },
      ],
      withOccurredAt: 32_000,
      withNarrativeTime: 400,
      withEntities: 4_100,
      withEmbedding: 31_900,
      reinforcedTotal: 44_000,
      maxReinforcementCount: 37,
      charactersWithMemories: 38,
    },
    characterBreakdown: {
      total: 41,
      vaultLinked: 40,
      vaultless: 1,
      npcs: 6,
      userControlled: 3,
      carinaAnswerers: 2,
      systemTransparent: 4,
      canDressThemselves: 30,
      canCreateOutfits: 12,
      coreWhisperOverrides: 5,
    },
    featureConfig: {
      concierge: {
        enabled: true,
        newChatsStartAs: 'moderated',
        autoSwitchAfterRefusals: 2,
        display: { mode: 'SHOW', showWarningBadges: true },
        desk: {
          textProfileSet: true,
          imageProfileSet: false,
          visionProfileSet: false,
          imagePromptProfileSet: true,
        },
        preScreen: {
          enabled: true,
          threshold: 0.7,
          scanTextChat: true,
          scanImagePrompts: true,
          scanImageGeneration: false,
          customClassificationPrompt: false,
        },
        summaryClassification: true,
      },
      contextCompression: { enabled: true, windowSize: 5, compressionTargetTokens: 800 },
      agentMode: { maxTurns: 10, defaultEnabled: false },
      storyBackgrounds: { enabled: true, hasDefaultImageProfile: true },
      timestamps: { mode: 'EVERY_MESSAGE', format: 'FRIENDLY' },
      autoLock: { enabled: false, idleMinutes: 15 },
      memoryCascade: {
        onMessageDelete: 'ASK_EVERY_TIME',
        onSwipeRegenerate: 'DELETE_MEMORIES',
      },
      autoDetectRng: true,
      customTools: true,
      avatarDisplay: { mode: 'ALWAYS', style: 'CIRCULAR' },
      coreWhisper: {
        enabled: true,
        interval: 12,
        silenceThreshold: 3,
        packetTokenBudget: 4096,
        fireOnContextTransition: true,
      },
      thinkingDisplay: { defaultVisible: true, defaultCollapsed: true },
      answerConfirmation: { enabled: false },
      autonomousRoomDefaults: { dailyTokenBudget: 1_000_000 },
      autoHousekeeping: {
        enabled: true,
        perCharacterCap: 2000,
        mergeSimilar: false,
        autoMergeSimilarThreshold: 0.9,
      },
      textReplacements: { enabled: true, rules: 12, enabledRules: 10 },
      composerSpellcheck: true,
      autoScrollOnResponseComplete: false,
      imageDescriptionProfileConfigured: true,
      uncensoredVisionProfileConfigured: false,
    },
    instanceSettings: {
      staleChatDays: 30,
      chatsEligibleForNextSweep: 14,
      maxConcurrentJobs: 4,
      memoryRecall: { scopePolicy: 'down-weight', expandRelated: false },
      memoryExtractionLimits: {
        enabled: true,
        maxPerHour: 20,
        softStartFraction: 0.7,
        softFloor: 0.7,
      },
      lastMaintenanceSweepAt: '2026-08-05T03:00:00.000Z',
    },
    backgroundJobs: {
      byStatus: [
        { status: 'COMPLETED', count: 4_000 },
        { status: 'PENDING', count: 12 },
        { status: 'FAILED', count: 3 },
      ],
      byType: [
        { type: 'MEMORY_EXTRACTION', count: 3_000 },
        { type: 'EMBEDDING_GENERATE', count: 1_015 },
      ],
      failed: [
        { type: 'EMBEDDING_GENERATE', count: 3, lastError: 'chunk exceeds 8192-token cap' },
      ],
      attemptsExhausted: 3,
      oldestPendingScheduledAt: '2026-08-05T11:00:00.000Z',
    },
    embeddingPipeline: {
      statusByEntityType: [
        { entityType: 'memory', status: 'EMBEDDED', count: 31_900 },
        { entityType: 'memory', status: 'FAILED', count: 156 },
      ],
      failed: 156,
      conversationChunks: { total: 9_000, unembedded: 40 },
      helpDocs: { total: 120, unembedded: 0 },
      storedDimensions: [
        { table: 'memories', dimensions: 1536, vectors: 31_900 },
        { table: 'conversation_chunks', dimensions: 1536, vectors: 8_960 },
      ],
      activeProfileDimensions: 1536,
      dimensionMismatch: false,
    },
    terminal: {
      totalSessions: 22,
      liveSessions: 1,
      nonZeroExits: 4,
      distinctShells: ['zsh', 'bash'],
    },
    storageStats: {
      totalFiles: 1_200,
      totalSize: 900_000_000,
      folders: [
        { path: '/reports', fileCount: 30, totalSize: 3_000_000 },
        { path: '/', fileCount: 1_170, totalSize: 897_000_000 },
      ],
      notOkFiles: 2,
      generatedImagesByModel: [{ generationModel: 'gpt-image-1', count: 410, bytes: 800_000_000 }],
    },

    scriptorium: {
      available: true,
      mountPoints: {
        total: 52,
        enabled: 50,
        byKind: [
          {
            mountType: 'database',
            storeType: 'character',
            count: 40,
            enabled: 40,
            fileCount: 900,
            chunkCount: 4_000,
            totalSizeBytes: 700_000_000,
          },
          {
            mountType: 'filesystem',
            storeType: 'documents',
            count: 12,
            enabled: 10,
            fileCount: 3_000,
            chunkCount: 20_000,
            totalSizeBytes: 300_000_000,
          },
        ],
        scanErrors: 1,
        conversionErrors: 1,
        scanStatuses: [
          { status: 'idle', count: 50 },
          { status: 'error', count: 2 },
        ],
        conversionStatuses: [
          { status: 'idle', count: 51 },
          { status: 'error', count: 1 },
        ],
        wellKnown: [
          {
            label: 'Quilltap Uploads',
            settingKey: 'userUploadsMountPointId',
            mountPointId: 'mp-uploads',
            name: 'Quilltap Uploads',
            resolved: true,
          },
          {
            label: 'Quilltap General',
            settingKey: 'generalMountPointId',
            mountPointId: null,
            name: null,
            resolved: false,
          },
        ],
      },
      content: {
        fileRows: 3_800,
        linkRows: 4_100,
        documentRows: 3_000,
        documentTextBytes: 40_000_000,
        blobRows: 800,
        blobBytes: 960_000_000,
        blobsByMimeType: [{ storedMimeType: 'image/webp', count: 780, bytes: 950_000_000 }],
        chunkRows: 24_000,
        unembeddedChunks: 156,
        chunkTokens: 6_000_000,
      },
      links: {
        dedupRatio: 1.0789473684210527,
        hardLinkGroups: 14,
        hardLinkedLinks: 31,
        extractionErrors: 2,
        conversionErrors: 1,
        policyEmbedDenied: 9,
        policyCharacterReadDenied: 4,
        policyCharacterWriteDenied: 11,
      },
      characterVaults: { total: 40, withKeystone: 39, missingKeystone: 1, withMetadata: 22 },
      wardrobe: [
        { tier: 'character', items: 410, archived: 38 },
        { tier: 'project', items: 12, archived: 0 },
        { tier: 'group', items: 0, archived: 0 },
        { tier: 'general', items: 60, archived: 4 },
      ],
      customTools: {
        total: 17,
        byStore: [{ store: 'Quilltap General', count: 12 }],
        withPresets: 5,
        presetFiles: 9,
        withLlmConsult: 3,
        withEffects: 6,
        metadataGated: 2,
        parseFailures: 1,
        parseFailureDetail: [
          {
            store: 'Quilltap General',
            path: 'Tools/broken.tool.json',
            reason: 'outcomes: last entry must be a catch-all',
          },
        ],
      },
      postOffice: { letters: 88, unannounced: 3, mailboxes: 14 },
      photos: {
        characterVaultPhotos: 640,
        characterVaultBytes: 800_000_000,
        userGalleryPhotos: 120,
        userGalleryBytes: 150_000_000,
      },
      scenarios: [
        { tier: 'character', count: 90, archived: 7 },
        { tier: 'project', count: 14, archived: 0 },
        { tier: 'group', count: 3, archived: 1 },
        { tier: 'general', count: 22, archived: 0 },
      ],
      stateCascade: {
        chatsWithState: 31,
        projectsWithState: 3,
        groupsWithState: 1,
        generalStatePresent: true,
      },
    },

    personae: {
      topCharacters: [
        { name: 'Friday', chats: 210, memories: 12_000, storageBytes: 90_000_000 },
        { name: 'Bertie', chats: 44, memories: 3_100, storageBytes: 12_000_000 },
      ],
      countsRemovedParticipants: true,
      projects: [
        { name: 'The Great Estate', linkedStores: 2, chats: 40, files: 120, documents: 300, hasState: true },
      ],
      groups: [
        {
          name: 'The Household',
          members: ['Bertie', 'Friday'],
          linkedStores: 1,
          hasOfficialStore: true,
        },
        { name: 'Orphans', members: [], linkedStores: 0, hasOfficialStore: false },
      ],
    },

    wireRecords: {
      totalEntries: 48_000,
      tokenUsage: { promptTokens: 9_000_000, completionTokens: 1_200_000, totalTokens: 10_200_000 },
      loggingEnabled: true,
      verboseMode: false,
      retentionDays: 30,
      exactProfileAttribution: true,
      byType: [
        {
          type: 'CHAT_MESSAGE',
          requests: 24_000,
          promptTokens: 8_000_000,
          completionTokens: 1_000_000,
          totalTokens: 9_000_000,
          measuredRequests: 23_000,
          avgDurationMs: 4_210.5,
          failures: 12,
        },
        {
          type: 'MEMORY_EXTRACTION',
          requests: 12_000,
          promptTokens: 600_000,
          completionTokens: 120_000,
          totalTokens: 720_000,
          measuredRequests: 400,
          avgDurationMs: 812,
          failures: 0,
        },
      ],
      connectionProfileLifetime: [
        {
          id: 'cp-1',
          name: 'Opus (household)',
          provider: 'anthropic',
          modelName: 'claude-opus-5',
          totalTokens: 8_000_000,
          totalPromptTokens: 7_000_000,
          totalCompletionTokens: 1_000_000,
          messageCount: 20_000,
          lastTouchedAt: '2026-08-05T10:00:00.000Z',
        },
      ],
      connectionProfileWindow: [
        {
          label: 'Opus (household)',
          provider: 'anthropic',
          modelName: 'claude-opus-5',
          requests: 20_000,
          promptTokens: 7_000_000,
          completionTokens: 1_000_000,
          totalTokens: 8_000_000,
          measuredRequests: 19_500,
          avgDurationMs: 4_400,
          medianDurationMs: 3_800,
          failures: 8,
        },
      ],
      imageProfileWindow: [
        {
          label: 'Lantern (OpenAI)',
          provider: 'openai',
          modelName: 'gpt-image-1',
          requests: 410,
          promptTokens: 0,
          completionTokens: 0,
          totalTokens: 0,
          measuredRequests: 410,
          avgDurationMs: 18_200,
          medianDurationMs: 17_400,
          failures: 6,
        },
      ],
      cacheByProvider: [
        {
          label: 'anthropic',
          rowsWithCacheUsage: 22_000,
          rowsWithCacheRead: 18_000,
          cacheReadTokens: 40_000_000,
          cacheCreationTokens: 3_000_000,
          uncachedPromptTokens: 7_000_000,
          requestHitRatio: 18_000 / 22_000,
          tokenHitRatio: 40_000_000 / 47_000_000,
        },
      ],
      cacheByProfile: [
        {
          label: 'Opus (household)',
          rowsWithCacheUsage: 20_000,
          rowsWithCacheRead: 17_000,
          cacheReadTokens: 38_000_000,
          cacheCreationTokens: 2_800_000,
          uncachedPromptTokens: 6_500_000,
          requestHitRatio: 17_000 / 20_000,
          tokenHitRatio: 38_000_000 / 44_500_000,
        },
      ],
    },

    ...overrides,
  }
}
