/**
 * Terminal Session Type Definitions
 *
 * Schemas and types for terminal session management, including
 * session metadata, WebSocket messages, and runtime state.
 *
 * @module schemas/terminal.types
 */

import { z } from 'zod';
import { UUIDSchema, TimestampSchema } from './common.types';

// ============================================================================
// DATABASE SCHEMA
// ============================================================================

/**
 * Terminal session record stored in the database
 */
export const TerminalSessionSchema = z.object({
  id: UUIDSchema,
  chatId: UUIDSchema,
  label: z.string().nullable().optional(),
  shell: z.string(),
  cwd: z.string(),
  startedAt: TimestampSchema,
  exitedAt: TimestampSchema.nullable().optional(),
  exitCode: z.number().int().nullable().optional(),
  transcriptPath: z.string().nullable().optional(),
  createdAt: TimestampSchema,
  updatedAt: TimestampSchema,
});

export type TerminalSession = z.infer<typeof TerminalSessionSchema>;

/**
 * Wire-level session metadata sent over the WebSocket and returned by REST endpoints.
 * Omits the BaseRepository-managed timestamps (createdAt/updatedAt); the session
 * lifecycle is captured by startedAt/exitedAt instead.
 */
export const PtySessionMetaSchema = TerminalSessionSchema.omit({
  createdAt: true,
  updatedAt: true,
});

export type PtySessionMeta = z.infer<typeof PtySessionMetaSchema>;

/**
 * Input variant for creating a new terminal session.
 * Fields like id, timestamps, and exitCode are optionally provided by the caller
 * but typically derived/generated by the spawn handler.
 */
export const TerminalSessionCreateSchema = z.object({
  id: UUIDSchema.optional(),
  chatId: UUIDSchema,
  label: z.string().nullable().optional(),
  shell: z.string().optional(),
  cwd: z.string().optional(),
  startedAt: TimestampSchema.optional(),
  exitedAt: TimestampSchema.nullable().optional(),
  exitCode: z.number().int().nullable().optional(),
  transcriptPath: z.string().nullable().optional(),
});

export type TerminalSessionCreate = z.infer<typeof TerminalSessionCreateSchema>;

// ============================================================================
// WEBSOCKET MESSAGE TYPES
// ============================================================================

/**
 * Client-to-server WebSocket message discriminated union
 */
export const WsClientMessageSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('input'),
    data: z.string(),
  }),
  z.object({
    type: z.literal('resize'),
    cols: z.number().int().positive(),
    rows: z.number().int().positive(),
  }),
  z.object({
    type: z.literal('ping'),
  }),
]);

export type WsClientMessage = z.infer<typeof WsClientMessageSchema>;

/**
 * Server-to-client WebSocket message discriminated union
 */
export const WsServerMessageSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('output'),
    data: z.string(),
  }),
  z.object({
    type: z.literal('exit'),
    code: z.number().int().nullable(),
    signal: z.string().nullable(),
  }),
  z.object({
    type: z.literal('meta'),
    meta: PtySessionMetaSchema,
  }),
  z.object({
    type: z.literal('pong'),
  }),
  z.object({
    type: z.literal('chat-update'),
    chatId: z.string(),
    reason: z.enum(['ariel-terminal-output']).optional(),
  }),
]);

export type WsServerMessage = z.infer<typeof WsServerMessageSchema>;
